//
// Created by diego on 9/10/2019.
//

#ifndef EJERCICIO__12_BUSCAMINAS_UNIDIMENSIONAL__BUSCAMINAS_H
#define EJERCICIO__12_BUSCAMINAS_UNIDIMENSIONAL__BUSCAMINAS_H

void gbombas(int x[100],int m,int c);

#endif //EJERCICIO__12_BUSCAMINAS_UNIDIMENSIONAL__BUSCAMINAS_H
